# Generated by Django 5.1.6 on 2025-03-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.PositiveBigIntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
