services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      default:
        ipv4_address: 172.19.0.2

  main_backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: bash -c "cd main_backend && uv sync && uv run python manage.py runserver 0.0.0.0:8000"
    networks:
      default:
        ipv4_address: 172.19.0.3  # Изменено на новый диапазон

  comments:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - main_backend
    command: bash -c "cd comments && uv sync && uv run fastapi dev --port 3000 --host 0.0.0.0"
    networks:
      default:
        ipv4_address: 172.19.0.4  # Изменено на новый диапазон

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16  # Подсеть остается прежней
